// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATBH56qgJzOG8Aya5xVyPGtbPaKOdMUd4',
    appId: '1:758602572142:web:803ff968978b0e22df217f',
    messagingSenderId: '758602572142',
    projectId: 'aiffelthon-scalp',
    authDomain: 'aiffelthon-scalp.firebaseapp.com',
    storageBucket: 'aiffelthon-scalp.appspot.com',
    measurementId: 'G-3H0FYLYQJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZC3qJQIxKyu3Y0N22lxhSGfwFWxEp_EI',
    appId: '1:758602572142:android:af1b2d087114908ddf217f',
    messagingSenderId: '758602572142',
    projectId: 'aiffelthon-scalp',
    storageBucket: 'aiffelthon-scalp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVK0INTg0glQEh8ufx_lbaBDql_5dh1M',
    appId: '1:758602572142:ios:b835b206690ddcc5df217f',
    messagingSenderId: '758602572142',
    projectId: 'aiffelthon-scalp',
    storageBucket: 'aiffelthon-scalp.appspot.com',
    iosClientId: '758602572142-srtvbdd82iot7rkg2s3kuljhare4efma.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiffelthon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVK0INTg0glQEh8ufx_lbaBDql_5dh1M',
    appId: '1:758602572142:ios:63bb8b4327c81313df217f',
    messagingSenderId: '758602572142',
    projectId: 'aiffelthon-scalp',
    storageBucket: 'aiffelthon-scalp.appspot.com',
    iosClientId: '758602572142-looasdo2632nhtf68456nromufntjpmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiffelthon.RunnerTests',
  );
}
