name: aiffelthon_hair
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  tflite_flutter: ^0.10.1
  image: ^4.0.17
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_signin_button: ^2.0.0
  sqflite: ^2.3.0
  http: ^1.1.0
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4
  webview_flutter_android: ^3.10.0
  flutter_colorpicker: ^1.0.3
  provider: ^6.0.5
  permission_handler: ^11.0.0
  flutter_uvc:
    path: lib/flutter_uvc/
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: DoHyeonRegular
      fonts:
        - asset: assets/fonts/DoHyeon-Regular.ttf
  uses-material-design: true
  assets:  
    - assets/model/model1.tflite
    - assets/model/model2.tflite
    - assets/model/model3.tflite
    - assets/model/model4.tflite
    - assets/model/model5.tflite
    - assets/model/model6.tflite
    - assets/images/shampoo1.png
    - assets/images/shampoo2.png
    - assets/images/shampoo3.png
    - assets/images/shampoo4.png
    - assets/images/shampoo5.png
    - assets/images/shampoo6.png
    - assets/images/shampoo7.png
    - assets/images/shampoo8.png
    - assets/images/fresh.png
    - assets/images/analysis.gif
    - assets/images/servey.gif
    - assets/images/history.gif
    


